version: '3'
services:
  hiking:
    image: 'hiking:latest'
    ports:
      - '8080:8080'
    depends_on:
      - hiking-db
    environment:
      SQL_USERNAME: 'postgres'
      SQL_PASSWORD: 'b00t200k4'
      SQL_DBNAME: 'hiking'
      SQL_HOST: 'hiking-db'
      SQL_PORT: '5432'
      API_HOST: '0.0.0.0'
  hiking-db:
    image: 'postgres'
    ports:
      - '25432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'b00t200k4'
      POSTGRES_DB: 'hiking'
